export interface ISite {
    siteID: number;
    siteNumber: number;
    siteName: string;
    when: string;
    address1: string;
    address2: string;
    address3: string;
    gradeLevels: string;
    phone: string;
    phoneType: string;
    timeAvailable: string;
    roomNumber: string;
    startTime: string;
    stopTime: string;
    startDate: string | null;
    full: number;
    min: number;
    daily: number;
    ampm: number;
    permit: string;
    issued: string | null;
    started: string | null;
    closed: string | null;
    expires: string | null;
    notes: string;
    autoRenew: boolean | string;
    originalContract: string | null;
    districtFee: string;
    dssRep: string;
    dssPhone: string;
    capacity: number | null;
    siteCapacity: number;
    class: string;
    county: string;
    principal: string;
    schoolPhone: string;
    closings: string;
    emergency: string;
    policeAddress1: string;
    policeAddress2: string;
    policeAddress3: string;
    policePhone: string;
    fireAddress1: string;
    fireAddress2: string;
    fireAddress3: string;
    firePhone: string;
    evacuation1Address1: string;
    evacuation1Address2: string;
    evacuation1Address3: string;
    evacuation1Phone: string;
    visitId: number;
    waitListDate: string;
    waitListCount: number;
    pcDate: string;
    pcAmount: number;
    transport: string;
    transportPhone: string;
    telephoneVolume: string;
    dataVolume: string;
    security: string;
    securityPhone: string;
    safePlace: string;
    lockdown: string;
    relocationRoom1: string;
    relocationRoom2: string;
    landlineLocation: string;
    additionalLocation: string;
    attendanceNote: string;
    sourceSchools: string;
    responsiblePerson: string;
    twoNames: string;
    hcpSent: string | null;
    hcpApproved: string | null;
    enrollment: number;
    coExp: string;
    waiverExp: string | null;
    nurseVisit: string | null;
    epiPen: boolean | string;
    inhaler: boolean | string;
    benadryl: boolean | string;
    hcpReviewed: string | null;
    secondNurseVisit: string | null;
    sFax: string;
    additionalLocation2: string;
    additionalLocation3: string;
    additionalLocation4: string;
    thirdNurseVisit: string | null;
    scopeFax: string;
    ascaP1: number;
    ascaP2: number;
    ascaP3: number;
    ascaP4: number;
    parentEmail: string | null;
    preKindergarten: boolean | string;
    universalPreKindergarten: boolean | string;
    evacuation2Address1: string;
    evacuation2Address2: string;
    evacuation2Address3: string;
    evacuation2Phone: string;
    ambulancePhone: string;
    additionalEmergencyInfo: string;
    roomNumber2: string;
    roomNumber3: string;
    roomNumber4: string;
    caP1: number;
    caP2: number;
    caP3: number;
    caP4: number;
    ossPlace: string;
    scopeEmail: string;
    scopePassword: string;
    midPoint: string;
    staffingAssistantName: string;
    staffingAssistantPhone: string;
    staffingAssistantFax: string;
    staffingAssistantEmail: string;
    staffingAssistantOthers: string;
    staffingAssistantExt: string;
    staffingAssistantForms: string;
    foodContactName: string;
    foodContactPhone: string;
    foodContactFax: string;
    foodContactEmail: string;
    foodContactOthers: string;
    foodContactExt: string;
    foodContactForms: string;
    supplyContactName: string;
    supplyContactPhone: string;
    supplyContactFax: string;
    supplyContactEmail: string;
    supplyContactOthers: string;
    supplyContactExt: string;
    supplyContactForms: string;
    pettyCashSpecialEventContactName: string;
    pettyCashSpecialEventContactPhone: string;
    pettyCashSpecialEventContactFax: string;
    pettyCashSpecialEventContactEmail: string;
    pettyCashSpecialEventContactOthers: string;
    pettyCashSpecialEventContactExt: string;
    pettyCashSpecialEventContactForms: string;
    fieldSupervisorName: string;
    fieldSupervisorPhone: string;
    fieldSupervisorFax: string;
    fieldSupervisorEmail: string;
    fieldSupervisorOthers: string;
    fieldSupervisorExt: string;
    fieldSupervisorForms: string;
    fieldTrainerName: string;
    fieldTrainerPhone: string;
    fieldTrainerFax: string;
    fieldTrainerEmail: string;
    fieldTrainerOthers: string;
    fieldTrainerExt: string;
    fieldTrainerForms: string;
    healthCareConsultantName: string;
    healthCareConsultantPhone: string;
    healthCareConsultantFax: string;
    healthCareConsultantEmail: string;
    healthCareConsultantOthers: string;
    healthCareConsultantExt: string;
    healthCareConsultantForms: string;
    registrarName: string;
    registrarPhone: string;
    registrarFax: string;
    registrarEmail: string;
    registrarOthers: string;
    registrarExt: string;
    registrarForms: string;
    accountBillingName: string;
    accountBillingPhone: string;
    accountBillingFax: string;
    accountBillingEmail: string;
    accountBillingOthers: string;
    accountBillingExt: string;
    accountBillingForms: string;
    substitutesName: string;
    substitutesPhone: string;
    substitutesFax: string;
    substitutesEmail: string;
    substitutesOthers: string;
    substitutesExt: string;
    substitutesForms: string;
    suppliesName: string;
    suppliesPhone: string;
    suppliesFax: string;
    suppliesEmail: string;
    suppliesOthers: string;
    suppliesExt: string;
    suppliesForms: string;
    accountAssistantOthers: string;
    type: number;
    priority: number;
    scopeDSSName: string;
    scopeDSSPhone: string;
    scopeDSSFax: string;
    scopeDSSEmail: string;
    scopeDSSOthers: string;
    scopeDSSExt: string;
    scopeDSSForms: string;
    presentersName: string;
    presentersPhone: string;
    presentersFax: string;
    presentersEmail: string;
    presentersOthers: string;
    presentersExt: string;
    presentersForms: string;
    accountAssistantName: string;
    accountAssistantPhone: string;
    accountAssistantFax: string;
    accountAssistantEmail: string;
}



export interface ISiteTable {
    siteID: number;
    siteName: string;
    permit: string;
    [key: string]: any;
}

export interface ISiteAssignmentTable {
    description: string;
    name: string;
    cell: string;
    ext: string;
    fax: string;
    email: string;
    forms: string;
    others: string;
}