// Define a union type for all modals
export type ModalType =
    'SITE-ASSIGNMENT-MODAL' |
    'CLOSING-MODAL' |
    'PERSONAL-TIMESHEET-MODAL' |
    'VISIT-BASICINFO-MODAL' |
    'STATUS-MODAL' |
    'CONTACT-MODAL' |
    'PERSONAL-TIMESHEET-SCHEDULE-MODAL' |
    'SCHEDULAR-TIMESHEET-MODAL' |
    'SCHEDULE-DATA-MODAL' |
    'PERSONAL_EXPERIENCE-MODAL'|
    'CERTIFICATE-MODAL'|
    'ATTANDANCE-MODAL'|
    'WAIVER-MODAL'|
    'CONFIRMATION-MODAL' |
    'PERSONAL-SCHEDULE-IMPORT-MODAL'|
    'TIMESHEET-FORM-MODAL'
    ;
